language: python
python:
  - '3.6'
sudo: false

branches:
  only:
    - master

install:
  - make ci-env

before_script:
  - pipenv install ./django-polls/dist/django-polls-0.1.tar.gz

script:
  - make test
